### ISSUE TITLE
Check copyright headers

### ISSUE THREAD

**Issue by danmarsden** [srobotta/moodle-report_ldapaccounts#4]
https://github.com/srobotta/moodle-report_ldapaccounts/blob/master/version.php#L22

Is this copy pasted from another plugin? If so you should check all your files and ensure the copyright header is defined correctly.

This is an approval blocker.

**Comment by srobotta** [comment]
The original plugin was developed by Luca Bösch of the BFH. I took the work, remodeled it into a generalized plugin not specific for the BFH. That's why these copyright statements have been there in the first place.
